name: rezume_app
description: An AI-powered resume builder.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management & Preferences
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Add this package for file uploading
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/rezoom_logo.png
    - assets/images/
    - assets/lang/